-- Additive, data-preserving tenant foundation. Deploy in a transaction during a maintenance window.
CREATE TYPE "SiteStatus" AS ENUM ('ACTIVE','PENDING','SUSPENDED','EXPIRED','ARCHIVED');
CREATE TYPE "SiteDomainType" AS ENUM ('SUBDOMAIN','CUSTOM');
CREATE TYPE "SiteDomainStatus" AS ENUM ('PENDING','VERIFIED','DISABLED','REJECTED');
CREATE TYPE "PanelSubscriptionStatus" AS ENUM ('ACTIVE','PAST_DUE','SUSPENDED','EXPIRED','CANCELED');
ALTER TYPE "TransactionType" ADD VALUE IF NOT EXISTS 'PANEL_RENT';
ALTER TYPE "TransactionType" ADD VALUE IF NOT EXISTS 'PANEL_RENEWAL';
ALTER TYPE "TransactionType" ADD VALUE IF NOT EXISTS 'PANEL_RENT_REFUND';

CREATE SEQUENCE sites_site_number_seq START 100001;
CREATE TABLE sites (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), site_number BIGINT NOT NULL DEFAULT nextval('sites_site_number_seq'), parent_site_id UUID, owner_user_id UUID, name VARCHAR(160) NOT NULL, slug VARCHAR(80) NOT NULL, status "SiteStatus" NOT NULL DEFAULT 'PENDING', depth INTEGER NOT NULL CHECK(depth >= 0), deleted_at TIMESTAMPTZ(3), created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT sites_site_number_key UNIQUE(site_number), CONSTRAINT sites_slug_key UNIQUE(slug), CONSTRAINT sites_parent_fk FOREIGN KEY(parent_site_id) REFERENCES sites(id), CONSTRAINT sites_no_self_parent CHECK(parent_site_id IS NULL OR parent_site_id <> id));
-- Stable identifier used by code, tests, and disaster recovery; existing entity IDs are untouched.
INSERT INTO sites(id, site_number, name, slug, status, depth) VALUES ('00000000-0000-4000-8000-000000000001',100000,'DichVu1st','dichvu1st','ACTIVE',0);
SELECT setval('sites_site_number_seq', GREATEST(100001,(SELECT max(site_number)+1 FROM sites)), false);

CREATE TABLE site_domains (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),site_id UUID NOT NULL REFERENCES sites(id),hostname VARCHAR(253) NOT NULL UNIQUE,type "SiteDomainType" NOT NULL,status "SiteDomainStatus" NOT NULL DEFAULT 'PENDING',is_primary BOOLEAN NOT NULL DEFAULT false,verification_token VARCHAR(128) NOT NULL,verified_at TIMESTAMPTZ(3),created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX site_domains_one_primary ON site_domains(site_id) WHERE is_primary AND status='VERIFIED';
CREATE INDEX site_domains_site_status_idx ON site_domains(site_id,status);
INSERT INTO site_domains(site_id,hostname,type,status,is_primary,verification_token,verified_at) VALUES ('00000000-0000-4000-8000-000000000001','dichvu1st.com','CUSTOM','VERIFIED',true,'root-domain',CURRENT_TIMESTAMP);

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['users','api_keys','wallets','wallet_transactions','payment_methods','deposits','services','orders','order_history','tickets','notifications','coupons','affiliates','referrals','affiliate_commissions','daily_report_snapshots','price_groups','price_group_history','audit_logs','login_history','settings'] LOOP EXECUTE format('ALTER TABLE %I ADD COLUMN site_id UUID',t); EXECUTE format('UPDATE %I SET site_id=$1 WHERE site_id IS NULL',t) USING '00000000-0000-4000-8000-000000000001'::uuid; EXECUTE format('ALTER TABLE %I ALTER COLUMN site_id SET NOT NULL',t); EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY(site_id) REFERENCES sites(id) NOT VALID',t,t||'_site_fk'); EXECUTE format('ALTER TABLE %I VALIDATE CONSTRAINT %I',t,t||'_site_fk'); END LOOP; END $$;
ALTER TABLE users DROP CONSTRAINT users_email_key; ALTER TABLE users DROP CONSTRAINT users_username_key;
CREATE UNIQUE INDEX users_site_email_key ON users(site_id,email); CREATE UNIQUE INDEX users_site_username_key ON users(site_id,username); CREATE INDEX users_site_status_created_idx ON users(site_id,status,created_at); CREATE INDEX users_site_number_idx ON users(site_id,user_number);
ALTER TABLE payment_methods DROP CONSTRAINT payment_methods_code_key; CREATE UNIQUE INDEX payment_methods_site_code_key ON payment_methods(site_id,code); CREATE INDEX payment_methods_site_active_sort_idx ON payment_methods(site_id,active,sort_order);
ALTER TABLE coupons DROP CONSTRAINT coupons_code_key; CREATE UNIQUE INDEX coupons_site_code_key ON coupons(site_id,code); CREATE INDEX coupons_site_active_dates_idx ON coupons(site_id,active,starts_at,ends_at);
ALTER TABLE price_groups DROP CONSTRAINT price_groups_code_key; ALTER TABLE price_groups DROP CONSTRAINT price_groups_name_key; CREATE UNIQUE INDEX price_groups_site_code_key ON price_groups(site_id,code); CREATE UNIQUE INDEX price_groups_site_name_key ON price_groups(site_id,name); CREATE INDEX price_groups_site_active_tier_idx ON price_groups(site_id,active,tier_order);
CREATE INDEX orders_site_status_updated_idx ON orders(site_id,status,updated_at); CREATE INDEX orders_site_created_idx ON orders(site_id,created_at); CREATE INDEX deposits_site_status_created_idx ON deposits(site_id,status,created_at); CREATE INDEX tickets_site_status_updated_idx ON tickets(site_id,status,updated_at); ALTER TABLE settings DROP CONSTRAINT settings_group_key_key; CREATE UNIQUE INDEX settings_site_group_key_key ON settings(site_id,"group","key");
ALTER TABLE sites ADD CONSTRAINT sites_owner_fk FOREIGN KEY(owner_user_id) REFERENCES users(id) NOT VALID;

CREATE TABLE panel_rental_plans (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),seller_site_id UUID NOT NULL REFERENCES sites(id),code VARCHAR(50) NOT NULL,name VARCHAR(120) NOT NULL,description TEXT,price DECIMAL(20,8) NOT NULL CHECK(price>=0),currency CHAR(3) NOT NULL,billing_days INTEGER NOT NULL CHECK(billing_days>0),max_direct_children INTEGER NOT NULL CHECK(max_direct_children>=0),max_depth INTEGER NOT NULL CHECK(max_depth>=1),allow_custom_domain BOOLEAN NOT NULL DEFAULT false,allow_panel_resale BOOLEAN NOT NULL DEFAULT false,allow_api BOOLEAN NOT NULL DEFAULT false,allow_themes BOOLEAN NOT NULL DEFAULT true,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(seller_site_id,code));
CREATE INDEX panel_plans_seller_active_idx ON panel_rental_plans(seller_site_id,active);
CREATE TABLE panel_subscriptions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),site_id UUID NOT NULL REFERENCES sites(id),seller_site_id UUID NOT NULL REFERENCES sites(id),plan_id UUID NOT NULL REFERENCES panel_rental_plans(id),renter_user_id UUID NOT NULL REFERENCES users(id),status "PanelSubscriptionStatus" NOT NULL DEFAULT 'ACTIVE',started_at TIMESTAMPTZ(3) NOT NULL,expires_at TIMESTAMPTZ(3) NOT NULL,grace_until TIMESTAMPTZ(3) NOT NULL,auto_renew BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX panel_subscriptions_site_status_idx ON panel_subscriptions(site_id,status); CREATE INDEX panel_subscriptions_seller_status_idx ON panel_subscriptions(seller_site_id,status); CREATE INDEX panel_subscriptions_expiry_idx ON panel_subscriptions(status,expires_at);
CREATE TABLE site_service_rules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),site_id UUID NOT NULL REFERENCES sites(id),service_id UUID NOT NULL REFERENCES services(id),active BOOLEAN NOT NULL DEFAULT true,pricing_mode "PricingMode" NOT NULL,fixed_rate DECIMAL(20,8),markup_percent DECIMAL(9,6),fixed_profit DECIMAL(20,8),min_profit DECIMAL(20,8) NOT NULL DEFAULT 0,min_override INTEGER,max_override INTEGER,created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(site_id,service_id),CHECK(min_override IS NULL OR max_override IS NULL OR min_override<=max_override));
CREATE INDEX site_service_rules_site_active_idx ON site_service_rules(site_id,active);
CREATE TABLE order_site_settlements (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),order_id BIGINT NOT NULL REFERENCES orders(id),child_site_id UUID NOT NULL REFERENCES sites(id),parent_site_id UUID NOT NULL REFERENCES sites(id),payer_user_id UUID NOT NULL REFERENCES users(id),upstream_rate DECIMAL(20,8) NOT NULL,upstream_charge DECIMAL(20,8) NOT NULL,refunded_amount DECIMAL(20,8) NOT NULL DEFAULT 0,created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(order_id,child_site_id),CHECK(refunded_amount>=0 AND refunded_amount<=upstream_charge));
CREATE INDEX order_settlements_parent_created_idx ON order_site_settlements(parent_site_id,created_at); CREATE INDEX order_settlements_payer_created_idx ON order_site_settlements(payer_user_id,created_at);
CREATE INDEX sites_parent_status_idx ON sites(parent_site_id,status); CREATE INDEX sites_owner_status_idx ON sites(owner_user_id,status); CREATE INDEX sites_status_created_idx ON sites(status,created_at);
