/** Browser API client shared by every authenticated customer screen. */
export const apiClientScript = String.raw`
const csrfCookie=()=>decodeURIComponent((document.cookie.split('; ').find(v=>v.startsWith('smm_csrf='))||'=').split('=').slice(1).join('='));
const errorMessages={AUTHENTICATION_REQUIRED:'Phiên đăng nhập đã hết hạn.',CSRF_INVALID:'Yêu cầu bảo mật không hợp lệ. Vui lòng tải lại trang.',PERMISSION_DENIED:'Bạn không có quyền thực hiện thao tác này.',INSUFFICIENT_BALANCE:'Số dư không đủ để tạo đơn.',QUANTITY_INVALID:'Số lượng không hợp lệ.',COUPON_NOT_FOUND:'Mã giảm giá không tồn tại.',COUPON_INVALID:'Mã giảm giá không hợp lệ.',COUPON_EXPIRED:'Mã giảm giá đã hết hạn.',COUPON_INACTIVE:'Mã giảm giá không hoạt động.',COUPON_MIN_AMOUNT:'Đơn hàng chưa đạt giá trị tối thiểu.',COUPON_LIMIT:'Mã giảm giá đã hết lượt sử dụng.',COUPON_USER_LIMIT:'Bạn đã dùng hết lượt của mã này.',AMOUNT_TOO_SMALL:'Số tiền thấp hơn mức tối thiểu.',AMOUNT_TOO_LARGE:'Số tiền vượt mức tối đa.',METHOD_UNAVAILABLE:'Phương thức thanh toán hiện không khả dụng.',ORDER_NOT_FOUND:'Không tìm thấy đơn hàng.',NETWORK_ERROR:'Không thể kết nối máy chủ. Vui lòng thử lại.',TIMEOUT:'Yêu cầu quá thời gian chờ. Vui lòng thử lại.'};
class ApiError extends Error{constructor(status,code,message){super(errorMessages[code]||message||'Không thể hoàn tất yêu cầu.');this.status=status;this.code=code}}
async function request(path,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),options.timeout||15000),method=options.method||'GET',headers={accept:'application/json',...(options.headers||{})};if(!['GET','HEAD'].includes(method)){headers['x-csrf-token']=csrfCookie();if(options.body!==undefined)headers['content-type']='application/json'}try{const response=await fetch(API+path,{method,credentials:'include',headers,signal:controller.signal,...(options.body!==undefined?{body:JSON.stringify(options.body)}:{})});const text=await response.text();let payload={};if(text){try{payload=JSON.parse(text)}catch{throw new ApiError(response.status,'INVALID_RESPONSE','Máy chủ trả về dữ liệu không hợp lệ.')}}if(response.status===401){if(location.pathname!='/login')location.href='/login';throw new ApiError(401,'AUTHENTICATION_REQUIRED')}if(!response.ok||payload.success===false){const error=payload.error||{};throw new ApiError(response.status,error.code,error.message)}return payload.data}catch(error){if(error instanceof ApiError)throw error;if(error?.name==='AbortError')throw new ApiError(0,'TIMEOUT');throw new ApiError(0,'NETWORK_ERROR')}finally{clearTimeout(timer)}}
const api={get:path=>request(path),post:(path,body,headers)=>request(path,{method:'POST',body,headers}),put:(path,body)=>request(path,{method:'PUT',body}),patch:(path,body)=>request(path,{method:'PATCH',body}),delete:(path,body)=>request(path,{method:'DELETE',body})};
const query=(path,params)=>path+'?'+new URLSearchParams(Object.entries(params).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>[k,String(v)])).toString();
`;
