import { escapeHtml, rootBranding, type TenantBranding } from "./branding.js";
export const brandMarkup = (tenant: TenantBranding = rootBranding) => `<a class="brand" href="/" aria-label="${escapeHtml(tenant.name)} - Trang chủ">${tenant.logoUrl ? `<img class="mark" src="${escapeHtml(tenant.logoUrl)}" alt="">` : `<span class="mark">${escapeHtml(tenant.monogram)}</span>`}<strong data-theme-content="brandTitle">${escapeHtml(tenant.name)}</strong></a>`;
export const brand = brandMarkup();
export const button = (label: string, href: string, secondary = false) =>
  `<a class="button${secondary ? " secondary" : ""}" href="${href}">${label}<span aria-hidden="true">→</span></a>`;
export const headerMarkup = (tenant: TenantBranding = rootBranding) => `<header class="header"><div class="container nav">${brandMarkup(tenant)}<nav aria-label="Điều hướng chính"><a href="/#services">Dịch vụ</a><a href="/#pricing">Bảng giá</a><a href="/#process">Cách hoạt động</a><a href="/#faq">Hỗ trợ</a></nav><div class="nav-actions"><a href="/login">Đăng nhập</a>${button("Bắt đầu ngay", "/register")}</div><button class="menu" aria-label="Mở menu" aria-expanded="false">☰</button></div></header>`;
export const footerMarkup = (tenant: TenantBranding = rootBranding) => { const email=tenant.supportEmail || (tenant.isRoot ? "support@dichvu1st.com" : ""); return `<footer><div class="container footer-grid">${brandMarkup(tenant)}<div><strong>Liên kết nhanh</strong><a href="/#services">Dịch vụ</a><a href="/#pricing">Bảng giá</a><a href="/#process">Cách hoạt động</a></div><div><strong>Hỗ trợ khách hàng</strong>${email ? `<a href="mailto:${escapeHtml(email)}">${escapeHtml(email)}</a>` : ""}<span data-theme-content="supportSummary">${escapeHtml(tenant.supportSummary || "Hỗ trợ khách hàng")}</span></div><div><strong>Chính sách</strong><span>Điều khoản dịch vụ</span><span>Chính sách bảo mật</span></div></div><div class="container copyright" data-theme-content="footerText">© 2026 ${escapeHtml(tenant.name)}. Tất cả quyền được bảo lưu.</div></footer>`; };
export const header = headerMarkup();
export const footer = footerMarkup();
export const primitives = `<div id="toast" class="toast" role="status" aria-live="polite"></div><dialog id="modal"><button class="icon-button" aria-label="Đóng">×</button></dialog><div class="drawer" aria-hidden="true"></div><template id="skeleton"><div class="skeleton"></div></template><template id="empty-state"><div class="empty">Chưa có dữ liệu.</div></template><template id="error-state"><div class="error">Không thể tải dữ liệu. <button>Thử lại</button></div></template>`;
