import { escapeHtml, rootBranding, type TenantBranding } from "./branding.js";
export const brandMarkup = (tenant: TenantBranding = rootBranding) => `<a class="brand" href="/" aria-label="${escapeHtml(tenant.name)} - Trang chủ" data-theme-node="header.brand" data-theme-node-type="text">${tenant.logoUrl ? `<img class="mark" src="${escapeHtml(tenant.logoUrl)}" alt="">` : `<span class="mark">${escapeHtml(tenant.monogram)}</span>`}<strong data-theme-node-label data-theme-content="brandTitle">${escapeHtml(tenant.name)}</strong></a>`;
export const brand = brandMarkup();
export const button = (label: string, href: string, secondary = false) =>
  `<a class="button${secondary ? " secondary" : ""}" href="${href}">${label}<span aria-hidden="true">→</span></a>`;
export const headerMarkup = (tenant: TenantBranding = rootBranding) => `<header class="header"><div class="container nav">${brandMarkup(tenant)}<nav aria-label="Điều hướng chính" data-theme-section="navigation" data-theme-slot="content"><a href="/#services" data-theme-node="nav.services" data-theme-node-type="link" data-i18n="nav.services">Dịch vụ</a><a href="/#pricing" data-theme-node="nav.pricing" data-theme-node-type="link" data-i18n="nav.pricing">Bảng giá</a><a href="/#process" data-theme-node="nav.process" data-theme-node-type="link" data-i18n="nav.how">Cách hoạt động</a><a href="/#faq" data-theme-node="nav.support" data-theme-node-type="link" data-i18n="nav.support">Hỗ trợ</a></nav><div class="nav-actions"><a href="/login" data-i18n="nav.login">Đăng nhập</a>${button("Bắt đầu ngay", "/register")}</div><button class="menu" aria-label="Mở menu" aria-expanded="false">☰</button></div></header>`;
export const footerMarkup = (tenant: TenantBranding = rootBranding) => { const email=tenant.supportEmail || (tenant.isRoot ? "support@dichvu1st.com" : ""); return `<footer data-theme-section="footer" data-theme-slot="content"><div class="container footer-grid">${brandMarkup(tenant)}<div><strong data-i18n="public.footer.links">Liên kết nhanh</strong><a href="/#services" data-i18n="nav.services">Dịch vụ</a><a href="/#pricing" data-i18n="nav.pricing">Bảng giá</a><a href="/#process" data-i18n="nav.how">Cách hoạt động</a></div><div><strong data-i18n="public.footer.support">Hỗ trợ khách hàng</strong>${email ? `<a href="mailto:${escapeHtml(email)}">${escapeHtml(email)}</a>` : ""}<span data-theme-content="supportSummary">${escapeHtml(tenant.supportSummary || "Hỗ trợ khách hàng")}</span></div><div><strong data-i18n="public.footer.policy">Chính sách</strong><span>Điều khoản dịch vụ</span><span>Chính sách bảo mật</span></div></div><div class="container copyright" data-theme-content="footerText">© 2026 ${escapeHtml(tenant.name)}. Tất cả quyền được bảo lưu.</div></footer>`; };
export const header = headerMarkup();
export const footer = footerMarkup();
export const primitives = `<div id="toast" class="toast" role="status" aria-live="polite"></div><dialog id="modal"><button class="icon-button" aria-label="Đóng">×</button></dialog><div class="drawer" aria-hidden="true"></div><template id="skeleton"><div class="skeleton"></div></template><template id="empty-state"><div class="empty">Chưa có dữ liệu.</div></template><template id="error-state"><div class="error">Không thể tải dữ liệu. <button>Thử lại</button></div></template>`;

/** Keep translated theme copy consistent with the request tenant. */
export const tenantI18nScript = (script: string, tenant: TenantBranding) =>
  script.replace("const normalise=", `const tenantName=${JSON.stringify(tenant.name).replace(/</g, "\\u003c")};for(const dictionary of Object.values(dicts))for(const key of Object.keys(dictionary))dictionary[key]=dictionary[key].replace(/DichVu1st/gi,()=>tenantName);const normalise=`);
