/** Every rule is rooted in an opt-in page marker; Aurora, AI and admin are untouched. */
export const referenceBaseStyles = `
:root[data-theme] [data-reference-page] .button{background:var(--ref-button-bg,var(--theme-primary));color:var(--ref-on-accent,#fff)}
:root[data-theme] .theme-custom-blocks{display:grid;gap:12px;width:min(1120px,calc(100% - 40px));margin:18px auto;padding:clamp(12px,2vw,24px);border:1px solid var(--theme-border);border-radius:var(--theme-radius);background:color-mix(in srgb,var(--theme-surface) 88%,transparent);color:var(--theme-text)}
:root[data-theme] .theme-custom-block{margin:0;color:inherit}
:root[data-theme] .theme-custom-block img{display:block;width:100%;max-height:520px;object-fit:cover;border-radius:var(--theme-radius)}
:root[data-theme] .theme-custom-block .button{display:inline-flex;width:max-content;max-width:100%}
:root[data-theme] .theme-custom-block[hidden]{display:none!important}
:root[data-theme] [data-reference-page] .button.secondary{background:var(--theme-surface);color:var(--theme-text);border-color:var(--theme-border)}
:root[data-theme] [data-reference-page] .sidebar nav a.active{background:var(--ref-nav-active,var(--theme-primary));color:var(--ref-nav-text,var(--ref-on-accent,#fff));box-shadow:none}
[data-reference-page] select{appearance:none;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 20 20'%3E%3Cpath d='m5 7 5 5 5-5' fill='none' stroke='%23818c9c' stroke-width='2'/%3E%3C/svg%3E")!important;background-repeat:no-repeat!important;background-position:right 12px center!important;background-size:18px!important;padding-right:40px!important}
.ref-tenant-logo{width:38px;height:38px;object-fit:contain;flex-shrink:0}
[data-reference-page] .field{border-radius:var(--theme-radius);overflow:hidden}
[data-reference-page] .field input:not([type=checkbox]):not([type=radio]){border:0;border-radius:0;background:transparent;box-shadow:none;outline-offset:-3px}
[data-reference-page] .bulk-steps{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;overflow:visible}
[data-reference-page] .bulk-steps>*{white-space:normal;background:var(--theme-surface);color:var(--theme-muted);border:1px solid var(--theme-border);border-radius:var(--theme-radius);font-size:13px;text-align:center;padding:10px}
[data-reference-page] .bulk-steps b{background:var(--theme-primary);color:var(--ref-on-accent,#fff)}
@media(max-width:600px){[data-reference-page] .bulk-steps{grid-template-columns:repeat(2,minmax(0,1fr))}}
.ref-customer .ref-order-mix{margin:16px 0}.ref-order-mix h2{font-size:20px}.ref-mix-body{display:flex;align-items:center;gap:22px;flex-wrap:wrap}.ref-donut{position:relative;flex:0 0 150px;width:150px;height:150px;border-radius:50%;background:conic-gradient(var(--theme-primary) var(--mix-done),var(--theme-secondary) var(--mix-done) var(--mix-active),var(--theme-border) var(--mix-active))}.ref-donut:before{content:'';position:absolute;inset:15px;border-radius:50%;background:var(--theme-surface)}.ref-donut>span{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center}.ref-donut b{font:700 28px var(--theme-font)}.ref-donut small{font-size:10px;color:var(--theme-muted)}.ref-mix-body dl{flex:1;min-width:110px;font-size:12px}.ref-mix-body dl>div{display:flex;justify-content:space-between;gap:16px;padding:7px 0;border-bottom:1px solid var(--theme-border)}.ref-mix-body dd{margin:0;font-weight:700}.ref-order-mix>p{font-size:11px}
[data-reference-page]{--bg:var(--theme-bg);--panel:var(--theme-surface);--line:var(--theme-border);--muted:var(--theme-muted);--cyan:var(--theme-primary);--white:var(--theme-text);color:var(--theme-text);font-family:var(--theme-font);line-height:1.55;min-width:0}
[data-reference-page] *{box-sizing:border-box;min-width:0}
[data-reference-page] h1{font-size:clamp(34px,4.5vw,68px);line-height:1.09;letter-spacing:-.045em;margin:20px 0;font-weight:800}
[data-reference-page] h1 em{display:block;color:var(--theme-primary);font-style:normal}
[data-reference-page] h2{font-size:clamp(21px,2.4vw,30px);line-height:1.2;letter-spacing:-.02em}
[data-reference-page] p{color:var(--theme-muted)}
[data-reference-page] a:focus-visible,[data-reference-page] button:focus-visible,[data-reference-page] input:focus-visible,[data-reference-page] select:focus-visible,[data-reference-page] textarea:focus-visible{outline:3px solid var(--theme-primary);outline-offset:4px}
.ref-page{max-width:1560px;margin:auto;padding:24px clamp(18px,4vw,64px)}
.ref-brand{display:inline-flex;align-items:center;gap:10px;font-size:clamp(18px,2vw,28px);font-weight:800;letter-spacing:-.04em}.ref-brand>span{font-size:38px;color:var(--theme-primary)}.ref-brand strong{overflow-wrap:anywhere}
.ref-nav{display:flex;align-items:center;justify-content:space-between;gap:22px;padding:16px 0;border-bottom:1px solid var(--theme-border)}.ref-nav nav,.ref-nav>div{display:flex;align-items:center;gap:24px;font-size:14px}.ref-nav nav a:hover{color:var(--theme-primary)}
.ref-cta,.ref-secondary{display:inline-flex;justify-content:center;align-items:center;padding:13px 24px;border:1px solid var(--theme-border);border-radius:var(--theme-radius);font-weight:750;min-height:46px}.ref-cta{background:var(--theme-primary);color:var(--ref-on-accent,#fff);box-shadow:0 8px 24px color-mix(in srgb,var(--theme-primary) 20%,transparent)}.ref-secondary{background:var(--theme-surface);color:var(--theme-text)}.ref-actions{display:flex;gap:14px;flex-wrap:wrap;margin:28px 0}.ref-copy>small{font-size:11px;letter-spacing:.17em;font-weight:750}.ref-copy>p{max-width:550px}.ref-scene{display:block;width:100%;height:100%;object-fit:cover}.ref-page figure,.ref-auth figure{margin:0;position:relative;overflow:hidden}.ref-page figcaption,.ref-auth figcaption{position:absolute;bottom:28px;left:28px;padding:14px;background:var(--theme-surface);color:var(--theme-text)}
.ref-assurances{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px;margin:0;padding:28px 0;border-block:1px solid var(--theme-border)}.ref-assurances dt{font-weight:800;font-size:23px;color:var(--theme-primary)}.ref-assurances dd{margin:0;font-size:12px;color:var(--theme-muted)}.ref-platforms{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px;padding:24px 0}.ref-platforms a{display:flex;align-items:center;justify-content:center;gap:10px;padding:14px 10px;border:1px solid var(--theme-border);border-radius:var(--theme-radius);background:var(--theme-surface);font-size:13px}.ref-platforms b{font:800 24px system-ui;color:var(--theme-primary)}
.ref-benefits{padding:28px 0}.ref-benefits>div{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.ref-benefits article{padding:24px;border:1px solid var(--theme-border);border-radius:var(--theme-radius);background:var(--theme-surface)}.ref-benefits article>b{font-size:32px;color:var(--theme-primary)}.ref-benefits h3{margin:10px 0}.ref-benefits p{font-size:14px}.ref-benefits a{font-size:13px;font-weight:700}
.ref-footer{display:flex;align-items:center;justify-content:space-between;gap:24px;background:none;padding:30px 0;color:var(--theme-muted);font-size:12px}.ref-page #pricing{padding:40px 0}.ref-page #pricing .container{width:100%}.ref-page .pricing-layout{grid-template-columns:1fr}.ref-page .section-title{font-size:32px;letter-spacing:-1px}.ref-page .gradient{color:var(--theme-primary);background:none}.ref-page .price{color:var(--theme-primary)}
.ref-auth{min-height:100vh;padding:clamp(18px,4vw,60px)}.ref-auth .auth-card{width:100%;max-width:520px;margin:auto;padding:clamp(22px,3vw,46px);box-shadow:none}.ref-auth .auth-card>p{color:var(--theme-muted)}.ref-auth .brand .mark{display:none}.ref-auth .brand{color:var(--theme-text);letter-spacing:-.03em}.ref-auth .field{background:var(--theme-surface);border-color:var(--theme-border)}.ref-auth .toggle,.ref-auth .auth-links a{color:var(--theme-primary)}.ref-auth .form-row{gap:12px;align-items:center;font-size:13px}.ref-auth .form-row label{display:flex;align-items:center;gap:8px;margin:0}
.ref-customer{min-height:100vh}.ref-customer .sidebar{position:static;width:100%;height:auto;min-height:100vh;overflow:auto;border:0;padding:20px 12px;background:none!important}.ref-customer .sidebar .brand{font-size:22px;padding:0 8px 22px}.ref-customer .sidebar .mark{display:none}.ref-customer .sidebar .brand strong,.ref-customer .sidebar nav span,.ref-customer .logout span{display:inline}.ref-customer .sidebar nav a{color:var(--theme-muted);justify-content:flex-start;font-size:13px}.ref-customer .sidebar nav a.active{color:var(--ref-on-accent,#fff);background:var(--theme-primary);box-shadow:none}.ref-customer .logout{position:static;width:100%;margin-top:24px;color:var(--theme-text);background:var(--theme-surface)}.ref-customer .customer-content{width:100%;padding:28px;max-width:1600px}.ref-customer .topbar{position:sticky;top:0;height:auto;min-height:76px;padding:14px 26px;gap:16px}.ref-customer .topbar>div:first-of-type{display:block}.ref-customer .topbar small{color:var(--theme-muted)}.ref-customer .balance,.ref-customer .profile,.ref-customer .icon-button{background:var(--theme-surface);color:var(--theme-text);border-color:var(--theme-border)}.ref-customer .balance b{color:var(--theme-text)}.ref-customer .profile{cursor:pointer}.ref-close{display:none}
[data-reference-page] :is(.panel,.card,.metric-card,.service-detail,.method,.wallet-hero,.conversation article,.raw-key){background:var(--theme-surface);color:var(--theme-text);border:1px solid var(--theme-border);border-radius:var(--theme-radius);box-shadow:none}
[data-reference-page] :is(input:not([type=checkbox]):not([type=radio]),select,textarea){width:100%;min-height:46px;padding:12px 14px;font:inherit;color:var(--theme-text);background:var(--theme-surface);border:1px solid var(--theme-border);border-radius:var(--theme-radius);max-width:100%}
[data-reference-page] .field input{border:0;background:transparent}[data-reference-page] textarea{min-height:160px;resize:vertical;display:block}[data-reference-page] :is(input[type=checkbox],input[type=radio]){width:18px;height:18px;accent-color:var(--theme-primary);flex-shrink:0}
[data-reference-page] label{font-size:14px;line-height:1.5;overflow-wrap:anywhere}[data-reference-page] button{font:inherit;cursor:pointer;min-height:40px}[data-reference-page] button:not(.toggle):not(.button):not(.profile):not(.icon-button){border:1px solid var(--theme-border);border-radius:var(--theme-radius);padding:10px 14px;color:var(--theme-text);background:var(--theme-surface)}
[data-reference-page] .button{background:var(--theme-primary);color:var(--ref-on-accent,#fff);border:1px solid transparent;box-shadow:none;font:700 14px/1.5 var(--theme-font);min-height:46px;border-radius:var(--theme-radius)}[data-reference-page] .button.secondary{background:var(--theme-surface);color:var(--theme-text);border-color:var(--theme-border)}[data-reference-page] button:disabled{opacity:.55;cursor:not-allowed}
[data-reference-page] :is(.meta,.muted,.service-card p,.service-detail span,.method span,.method small,.account-grid span,th){color:var(--theme-muted)}[data-reference-page] .eyebrow{color:var(--theme-primary);border-color:var(--theme-border)}[data-reference-page] .eyebrow:before{display:none}[data-reference-page] .step-title i{background:var(--theme-primary);color:var(--ref-on-accent,#fff)}[data-reference-page] .form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}[data-reference-page] .full-width{grid-column:1/-1}[data-reference-page] .table-wrap{max-width:100%;overflow:auto}[data-reference-page] .list-row{overflow-wrap:anywhere}[data-reference-page] .error-state{padding:28px}[data-reference-page] .form-message,[data-reference-page] .error{color:var(--ref-error,#b42343)}[data-reference-page] .form-message.success{color:var(--ref-success,#13734c)}[data-reference-page] .skeleton{background:linear-gradient(90deg,var(--theme-surface),var(--theme-border),var(--theme-surface));background-size:200%}
.ref-overview-heading{display:flex;align-items:center;justify-content:space-between;gap:22px;margin-bottom:24px}.ref-overview-heading h1{font-size:36px;margin:8px 0}.ref-overview-heading small{font-size:10px;letter-spacing:.16em}.ref-overview-heading p{margin:0;font-size:14px}.ref-shortcuts{display:grid;gap:12px}.ref-shortcuts a{padding:18px;border:1px solid var(--theme-border);border-radius:var(--theme-radius);background:var(--theme-surface);font-weight:700}.ref-customer .metric-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.ref-customer .metric-card b{font-size:clamp(22px,2.2vw,32px);overflow-wrap:anywhere}.ref-customer .quick-grid a{color:var(--theme-primary)}
@media(max-width:1100px){.ref-nav{flex-wrap:wrap}.ref-nav nav{order:3;width:100%;justify-content:center}.ref-customer .topbar .profile span{display:none}.ref-customer .metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.ref-customer .service-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:800px){.ref-benefits>div{grid-template-columns:repeat(2,minmax(0,1fr))}.ref-platforms{grid-template-columns:repeat(3,minmax(0,1fr))}.ref-customer .customer-content{padding:20px}.ref-customer .sidebar{min-height:0;height:100%;padding-top:12px}.ref-customer .icon-button{display:block}.ref-customer .topbar>div:first-of-type{display:none}.ref-customer .top-actions{margin-left:auto}.ref-customer .top-actions>.icon-button{display:none}.ref-customer .ref-close{display:block;margin:12px}.ref-customer [data-ref-rail]{position:fixed!important;inset:0 auto 0 0!important;width:260px!important;height:100dvh!important;background:var(--theme-surface)!important;z-index:50;transform:translateX(-105%);transition:transform .2s;overflow:auto;box-shadow:15px 0 50px #0005}.ref-customer [data-ref-rail]:has(.sidebar.open){transform:none}.ref-customer .sidebar.open{position:static;box-shadow:none}.ref-customer .sidebar{left:auto}.ref-customer .order-layout,.ref-customer .deposit-layout{grid-template-columns:1fr}.ref-overview-heading{align-items:flex-start}.ref-overview-heading h1{font-size:30px}}
@media(max-width:520px){[data-reference-page] h1{font-size:36px;letter-spacing:-.04em}.ref-nav{gap:12px}.ref-nav nav{gap:18px;justify-content:flex-start;overflow:auto;font-size:12px}.ref-nav>div{gap:12px;font-size:12px}.ref-nav .ref-cta{padding:10px 12px}.ref-brand{font-size:20px}.ref-assurances{grid-template-columns:1fr 1fr}.ref-assurances dt{font-size:19px}.ref-platforms a{flex-direction:column;font-size:11px}.ref-benefits>div{grid-template-columns:1fr}.ref-footer{flex-wrap:wrap}.ref-page .catalog{grid-template-columns:1fr}.ref-auth{padding:18px}.ref-auth .auth-card{padding:22px 18px}.ref-auth .auth-card h2{font-size:25px}.ref-customer .customer-content{padding:18px 14px}.ref-customer .topbar{padding:10px 14px}.ref-customer .balance{padding:6px 10px}.ref-customer .top-actions{gap:8px}.ref-customer .metric-card{padding:16px 12px}.ref-customer .metric-card b{font-size:22px}.ref-customer .service-grid,.ref-customer .quick-grid,[data-reference-page] .form-grid{grid-template-columns:1fr}.ref-overview-heading{flex-direction:column}.ref-customer .filter-bar{display:grid;grid-template-columns:1fr}.ref-customer .page-head{flex-wrap:wrap}.ref-customer .coupon{grid-template-columns:1fr}.ref-customer .notification{flex-wrap:wrap}.ref-customer .conversation article{max-width:100%}}
@media(prefers-reduced-motion:reduce){[data-reference-page] *{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
:root[data-theme="CREATOR_POP"] .pop-customer .customer-content :is(.panel,.metric-card,.table-wrap,.filter-bar,.empty,.error-state){border-color:#f0b8d8;border-radius:22px;box-shadow:0 10px 28px #c9277a12;background:#fff}
:root[data-theme="URBAN_LIME_BRUTAL"] .urban-customer .customer-content :is(.panel,.metric-card,.table-wrap,.filter-bar,.empty,.error-state){border:2px solid #30372c;border-radius:0;box-shadow:4px 4px 0 #d2ff00;background:#121712;color:#f3f5ed}
:root[data-theme="CYBER_NEON_CITY"] .cyber-customer .customer-content :is(.panel,.metric-card,.table-wrap,.filter-bar,.empty,.error-state){border:1px solid #34506f;border-radius:12px;box-shadow:0 0 22px #39cfff12;background:linear-gradient(145deg,#101a32,#0a1121)}
:root[data-theme="PRISM_GLASS"] .prism-customer .customer-content :is(.panel,.metric-card,.table-wrap,.filter-bar,.empty,.error-state){border:1px solid #fff;border-radius:20px;background:#ffffff9c;box-shadow:0 12px 35px #576cb51a;backdrop-filter:blur(16px)}
:root[data-theme="OCEAN_PREMIUM"] .ocean-customer .customer-content :is(.panel,.metric-card,.table-wrap,.filter-bar,.empty,.error-state){border:1px solid #24516a;border-radius:16px;background:linear-gradient(150deg,#08283d,#061e30);box-shadow:0 12px 30px #00162255}
:root[data-theme="BLUE_BUSINESS"] .blue-customer .customer-content :is(.panel,.metric-card,.table-wrap,.filter-bar,.empty,.error-state){border:1px solid #dbe5f1;border-radius:12px;background:#fff;box-shadow:0 5px 18px #174f9012}
:root[data-theme="ZEN_JAPANESE"] .zen-customer .customer-content :is(.panel,.metric-card,.table-wrap,.filter-bar,.empty,.error-state){border:1px solid #d6ddcf;border-radius:2px;background:#fbfcf6;box-shadow:none}
:root[data-theme="BLACK_GOLD_LUXURY"] .gold-customer .customer-content :is(.panel,.metric-card,.table-wrap,.filter-bar,.empty,.error-state){border:1px solid #5b4b32;border-radius:8px;background:linear-gradient(150deg,#171813,#0d100e);box-shadow:0 12px 32px #0005}
:root[data-theme="BEIGE_EDITORIAL"] .beige-customer .customer-content :is(.panel,.metric-card,.table-wrap,.filter-bar,.empty,.error-state){border:1px solid #d9cbb5;border-radius:0;background:#fffdf8;box-shadow:0 4px 15px #7c62320a}
:root[data-theme="PRISM_GLASS"] [data-reference-page] .prism-message h1,:root[data-theme="PRISM_GLASS"] [data-reference-page] .prism-auth-island h1,:root[data-theme="OCEAN_PREMIUM"] [data-reference-page] .ocean-horizon h1,:root[data-theme="OCEAN_PREMIUM"] [data-reference-page] .ocean-heading-band h1,:root[data-theme="ZEN_JAPANESE"] [data-reference-page] .zen-landscape h1,:root[data-theme="ZEN_JAPANESE"] [data-reference-page] .zen-opening h1,:root[data-theme="BLACK_GOLD_LUXURY"] [data-reference-page] .gold-monument h1,:root[data-theme="BLACK_GOLD_LUXURY"] [data-reference-page] .gold-summary-title h1{font-family:"Times New Roman",Georgia,"DejaVu Serif",serif!important;letter-spacing:0!important;font-feature-settings:normal}
:root[data-theme] [data-reference-page] .customer-content :is(.panel,.metric-card,.service-card,.table-wrap,.filter-bar,.list-row,.pagination,.notification,.method,.account-grid,.conversation article){color:var(--theme-text)}
:root[data-theme] [data-reference-page] .customer-content :is(input:not([type=checkbox]):not([type=radio]),select,textarea){color:var(--theme-text);background:var(--theme-surface);border-color:var(--theme-border);border-radius:var(--theme-radius)}
:root[data-theme] [data-reference-page] .customer-content :is(.status,.badge,.pagination .active){border-radius:var(--theme-radius)}
html[data-theme] [data-theme-node][hidden],html[data-theme] [data-theme-artwork][hidden]{display:none!important}
[data-theme-custom-blocks]{display:grid;gap:12px;margin-block:12px}[data-theme-custom-blocks][data-theme-custom-blocks-section="features"]{grid-column:1/-1}.theme-custom-block{max-width:100%;overflow-wrap:anywhere}.theme-custom-block-image img{display:block;max-width:min(100%,680px);height:auto;object-fit:cover;border-radius:var(--theme-radius)}[data-theme-section="hero"][data-theme-preset="centered"]{text-align:center;margin-inline:auto}[data-theme-section="hero"][data-theme-preset="centered"] :is(.ref-actions,.aiv3-actions){justify-content:center}[data-theme-section="hero"][data-theme-preset="wide"]{width:100%;max-width:none}[data-theme-section="hero"][data-theme-preset="compact"]{min-height:0;padding-block:20px}[data-theme-section="hero"][data-theme-preset="overlay"]{background:color-mix(in srgb,var(--theme-surface) 72%,transparent)}[data-theme-section="features"][data-theme-preset$="-column"]>div{grid-template-columns:repeat(2,minmax(0,1fr))}[data-theme-section="features"][data-theme-preset="3-column"]>div{grid-template-columns:repeat(3,minmax(0,1fr))}[data-theme-section="features"][data-theme-preset="4-column"]>div{grid-template-columns:repeat(4,minmax(0,1fr))}[data-theme-section="navigation"][data-theme-preset="centered"]{justify-content:center}[data-theme-section="navigation"][data-theme-preset="compact"]{gap:10px;padding-block:8px}[data-theme-section="navigation"][data-theme-preset="split"]{justify-content:space-between}
`;
