import { OrderError, orderAmount } from "./service.js";
import { moneyText, moneyUnits } from "../catalog/pricing.js";
const SCALE=100_000_000n;
const units=moneyUnits;
const text=moneyText;
export interface SettlementEdge {childSiteId:string;parentSiteId:string;payerUserId:string;upstreamRate:string;upstreamCharge:string}
export class SiteSettlementService {
 constructor(private readonly db:any){}
 async quote(tx:any,siteId:string,service:any,quantity:number):Promise<SettlementEdge[]>{
  const chain:any[]=[];let site=await tx.site.findUnique({where:{id:siteId}}),guard=0;
  while(site && site.id!==service.siteId && site.parentSiteId){if(++guard>64)throw new OrderError("SITE_HIERARCHY_INVALID","Invalid hierarchy");chain.push(site);site=await tx.site.findUnique({where:{id:site.parentSiteId}})}
  if(!site || site.id!==service.siteId)throw new OrderError("SERVICE_UNAVAILABLE","Service source is not an ancestor");chain.reverse();let rate=String(service.rate),parent=site,edges:SettlementEdge[]=[];
  for(const child of chain){const rule=await tx.siteServiceRule.findUnique({where:{siteId_serviceId:{siteId:child.id,serviceId:service.id}}});if(!rule?.active)throw new OrderError("SERVICE_UNAVAILABLE","Service is not inherited");const upstreamRate=rate;if(rule.fixedRate!=null)rate=String(rule.fixedRate);else {const base=units(rate),percent=units(rule.markupPercent??0);const fixed=units(rule.fixedProfit??0),minimum=units(rule.minProfit??0);rate=text(base+(base*percent/(100n*SCALE))+(fixed>minimum?fixed:minimum))}if(units(rate)<units(upstreamRate))throw new OrderError("SITE_PRICE_BELOW_COST","Panel price is below upstream cost");if(!child.ownerUserId)throw new OrderError("SITE_OWNER_MISSING","Panel owner missing");edges.push({childSiteId:child.id,parentSiteId:parent.id,payerUserId:child.ownerUserId,upstreamRate,upstreamCharge:orderAmount(upstreamRate,quantity)});parent=child}
  return edges;
 }
 async debitAndSnapshot(tx:any,order:any,edges:SettlementEdge[]){for(const edge of edges){const rows=await tx.$queryRawUnsafe('UPDATE "wallets" SET "balance"="balance"-$1::numeric,"version"="version"+1 WHERE "user_id"=$2::uuid AND "site_id"=$3::uuid AND "balance">=$1::numeric RETURNING "id","balance"+$1::numeric AS "before","balance" AS "after"',edge.upstreamCharge,edge.payerUserId,edge.parentSiteId);if(!rows[0])throw new OrderError("PANEL_UPSTREAM_BALANCE_LOW","Upstream panel balance is insufficient");await tx.walletTransaction.create({data:{siteId:edge.parentSiteId,walletId:rows[0].id,userId:edge.payerUserId,type:"ORDER",amount:`-${edge.upstreamCharge}`,balanceBefore:rows[0].before,balanceAfter:rows[0].after,referenceId:order.publicId,idempotencyKey:`settlement:${order.publicId}:${edge.childSiteId}`,description:"Panel upstream order charge"}});await tx.orderSiteSettlement.create({data:{orderId:order.id,...edge}})}}
 async refund(tx:any,order:any,remains:number){const rows=await tx.orderSiteSettlement.findMany({where:{orderId:order.id}});for(const row of rows){const target=units(row.upstreamCharge)*BigInt(remains)/BigInt(order.quantity),already=units(row.refundedAmount);if(target<already)throw new OrderError("REFUND_REVERSAL_UNSAFE","Refund target cannot decrease");if(target===already)continue;const delta=text(target-already),wallet=await tx.wallet.findFirstOrThrow({where:{userId:row.payerUserId,siteId:row.parentSiteId}}),updated=await tx.wallet.update({where:{id:wallet.id},data:{balance:{increment:delta},version:{increment:1}}});await tx.walletTransaction.create({data:{siteId:row.parentSiteId,walletId:wallet.id,userId:row.payerUserId,type:"REFUND",amount:delta,balanceBefore:wallet.balance,balanceAfter:updated.balance,referenceId:String(order.publicId),idempotencyKey:`settlement-refund:${order.publicId}:${row.childSiteId}:${target}`,description:"Panel upstream partial refund"}});await tx.orderSiteSettlement.update({where:{id:row.id},data:{refundedAmount:text(target)}})}}
}
